import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    sidebar: {
        width: Platform.OS === 'web' ? 450 : '85%',
        backgroundColor: '#f8f9fa',
        height: '100%',
        borderTopLeftRadius: 24,
        borderBottomLeftRadius: 24,
        shadowColor: '#000',
        shadowOffset: { width: -5, height: 0 },
        shadowOpacity: 0.1,
        shadowRadius: 15,
        elevation: 10,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 25,
        backgroundColor: '#fff',
        borderTopLeftRadius: 24,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    title: {
        fontSize: 22,
        fontWeight: '800',
        color: '#1a1a1a',
    },
    closeBtn: {
        width: 36,
        height: 36,
        backgroundColor: '#f0f0f0',
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    closeIcon: {
        fontSize: 22,
        color: '#666',
        fontWeight: 'bold',
        lineHeight: 24,
    },
    formContainer: {
        padding: 25,
        paddingBottom: 40,
    },
    inputLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: '#666',
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    inputField: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        marginBottom: 20,
        color: '#333',
    },
    infoBox: {
        backgroundColor: '#e8f5e9',
        padding: 15,
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#00D26A',
        marginTop: 10,
    },
    infoText: {
        color: '#2e7d32',
        fontSize: 13,
        lineHeight: 18,
    },
    footer: {
        padding: 20,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    saveBtn: {
        backgroundColor: '#00D26A',
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#00D26A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    saveBtnText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 1,
    }
});