import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f4f4f9',
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 50,
        paddingHorizontal: 20,
        marginBottom: 10,
    },
    backButton: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        backgroundColor: '#e6e6e6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    backArrow: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
    },
    title: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#000',
    },
    content: {
        paddingHorizontal: 25,
        paddingBottom: 50,
    },
    staticText: {
        fontSize: 14,
        color: '#333',
        marginBottom: 20,
        marginLeft: 5,
    },
    label: {
        fontSize: 14,
        color: '#333',
        marginBottom: 5,
        marginLeft: 5,
    },
    input: {
        backgroundColor: '#BCAE9B',
        borderRadius: 25,
        paddingVertical: 15,
        paddingHorizontal: 20,
        fontSize: 16,
        color: '#000',
        marginBottom: 15,
    },
    generateBtn: {
        backgroundColor: '#8CC63F',
        borderRadius: 25,
        paddingVertical: 15,
        alignItems: 'center',
        marginBottom: 20,
    },
    generateBtnText: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'Times New Roman',
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
    },
    submitBtn: {
        backgroundColor: '#7DBA45',
        flex: 0.48,
        borderRadius: 20,
        paddingVertical: 15,
        alignItems: 'center',
    },
    cancelBtn: {
        backgroundColor: '#ff1a1a',
        flex: 0.48,
        borderRadius: 20,
        paddingVertical: 15,
        alignItems: 'center',
    },
    btnText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'Times New Roman',
    },
    searchRow: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginBottom: 15,
        alignItems: 'center',
    },
    searchContainer: {
        flex: 1,
        marginRight: 15,
    },
    newButton: {
        backgroundColor: '#7DBA45',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    newButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    card: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderLeftWidth: 5,
        borderLeftColor: '#BCAE9B', // Khaki accent from manufacturing styles
    },
    cardExpanded: {
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
    },
    itemName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2c2c4d',
        marginBottom: 5,
    },
    itemDetail: {
        fontSize: 14,
        color: '#666',
    },
    itemStock: {
        fontSize: 16,
        fontWeight: '900',
    },
    actionRow: {
        flexDirection: 'row',
        backgroundColor: '#f9f9f9',
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
        borderWidth: 1,
        borderColor: '#eee',
        borderTopWidth: 0,
        overflow: 'hidden',
    },
    updateBtn: {
        flex: 1,
        backgroundColor: '#7DBA45',
        paddingVertical: 12,
        alignItems: 'center',
    },
    deleteBtn: {
        flex: 1,
        backgroundColor: '#DE3931',
        paddingVertical: 12,
        alignItems: 'center',
    },
    actionBtnText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 14,
    },
    recipeDivider: {
        height: 2,
        backgroundColor: '#ccc',
        marginVertical: 25,
    },
    recipeBuilderContainer: {
        backgroundColor: '#e8e6e1', // Light khaki background to separate it visually
        padding: 15,
        borderRadius: 15,
        marginBottom: 15,
    },
    addMaterialBtn: {
        backgroundColor: '#2c2c4d', // Dark purple to match your secondary brand color
        paddingVertical: 12,
        borderRadius: 20,
        alignItems: 'center',
        marginTop: 5,
    },
    addMaterialBtnText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    recipeListCard: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#BCAE9B',
        marginTop: 10,
    },
    recipeListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    }, 
    rowInputContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 15,
        gap: 10,
    },
    halfInput: {
        flex: 0.5,
        marginBottom: 0, 
    },
    halfDropdown: {
        flex: 0.5,
    },
    tabContainer: {
        flexDirection: 'row',
        marginHorizontal: 20,
        marginBottom: 15,
        backgroundColor: '#e8e6e1',
        borderRadius: 8,
        padding: 4,
    },
    tab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 6,
    },
    activeTab: {
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    tabText: {
        fontSize: 16,
        color: '#666',
        fontWeight: 'bold',
    },
    activeTabText: {
        color: '#2c2c4d',
    },
    rowInputContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 15,
        gap: 10,
    },
    halfInput: {
        flex: 0.5,
        marginBottom: 0, 
    },
    halfDropdown: {
        flex: 0.5,
    },
    recipeDivider: {
        height: 2,
        backgroundColor: '#ccc',
        marginVertical: 25,
    },
    recipeBuilderContainer: {
        backgroundColor: '#e8e6e1', 
        padding: 15,
        borderRadius: 15,
        marginBottom: 15,
    },
    addMaterialBtn: {
        backgroundColor: '#2c2c4d', 
        paddingVertical: 12,
        borderRadius: 20,
        alignItems: 'center',
        marginTop: 5,
    },
    addMaterialBtnText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    recipeListCard: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#BCAE9B',
        marginTop: 10,
    },
    recipeListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    dateFilterContainer: {
        marginBottom: 15,
    },
    historyCard: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 10,
        marginBottom: 12,
        borderLeftWidth: 5,
        borderLeftColor: '#7DBA45',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    historyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 5,
    },
    historyItemName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2c2c4d',
        flex: 1,
    },
    yieldBadge: {
        backgroundColor: '#e8f5e9',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 20,
    },
    yieldText: {
        color: '#2e7d32',
        fontWeight: 'bold',
        fontSize: 12,
    },
    historyDate: {
        fontSize: 14,
        color: '#666',
        marginTop: 5,
    }
});